# Simpler format to eliminate (unnecessary elements)
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""


[python]
# Show virtualenv only but no symbol and version number
format = '[\($virtualenv\)]($style) '
